def Test1(): #Test1
  TestedApps.UntitledCarGame.Run()
  winFormsGameForm = Aliases.UntitledCarGame.WinFormsGameForm
  OCR.Recognize(winFormsGameForm).BlockByText("New Race").Click()
  winFormsGameForm.Click(449, 179)
  winFormsGameForm.Keys("map.bmp")
  OCR.Recognize(winFormsGameForm).BlockByText("Submit", spLeftMost).Click()
  winFormsGameForm.Click(309, 330)
  winFormsGameForm.Click(516, 482)
  winFormsGameForm.Keys("car.txt")
  OCR.Recognize(winFormsGameForm).BlockByText("Submit", spNearestToCenter).Click()
  winFormsGameForm.Click(568, 532)
  winFormsGameForm.Keys("car.txt")
  OCR.Recognize(winFormsGameForm).BlockByText("Submit", spBottomMost).Click()
  OCR.Recognize(winFormsGameForm).BlockByText("Start").Click()
  winFormsGameForm.Close()
​
def Test2(): #Test2
  TestedApps.UntitledCarGame.Run()
  winFormsGameForm = Aliases.UntitledCarGame.WinFormsGameForm
  OCR.Recognize(winFormsGameForm).BlockByText("Race").Click()
  winFormsGameForm.Drag(484, 184, 5, -12)
  winFormsGameForm.Keys("map.bmp")
  OCR.Recognize(winFormsGameForm).BlockByText("Submit", spLeftMost).Click()
  winFormsGameForm.Click(308, 331)
  winFormsGameForm.Click(579, 482)
  winFormsGameForm.Keys("car.txt")
  OCR.Recognize(winFormsGameForm).BlockByText("Submit", spNearestToCenter).Click()
  winFormsGameForm.Click(551, 537)
  winFormsGameForm.Keys("car.txt")
  winFormsGameForm.Click(808, 532)
  OCR.Recognize(winFormsGameForm).BlockByText("Race").Click()
  winFormsGameForm.Close()
​
def Test3(): #Test 1 with drag instructions instead of click instructions
  TestedApps.UntitledCarGame.Run()
  winFormsGameForm = Aliases.UntitledCarGame.WinFormsGameForm
  winFormsGameForm.Drag(460, 541, 43, 0)
  winFormsGameForm.Drag(419, 180, 54, 7)
  winFormsGameForm.Keys("map.bmp")
  winFormsGameForm.Drag(636, 179, 38, 6)
  winFormsGameForm.Drag(307, 326, 38, 0)
  winFormsGameForm.Drag(536, 475, 33, 0)
  winFormsGameForm.Keys("car.txt")
  winFormsGameForm.Drag(762, 480, 49, 4)
  winFormsGameForm.Drag(596, 525, 38, 0)
  winFormsGameForm.Keys("car.txt")
  winFormsGameForm.Drag(761, 529, 50, 4)
  winFormsGameForm.Drag(291, 628, 34, -1)
  winFormsGameForm.Close()
​
def Test4(): #Test3 + main menu test
  TestedApps.UntitledCarGame.Run()
  winFormsGameForm = Aliases.UntitledCarGame.WinFormsGameForm
  winFormsGameForm.Drag(466, 542, 31, -2)
  winFormsGameForm.Drag(581, 631, 35, 1)
  winFormsGameForm.Drag(457, 542, 28, 5)
  winFormsGameForm.Drag(397, 181, 46, 2)
  winFormsGameForm.Keys("bmp[BS][BS][BS][BS]map.bmp")
  winFormsGameForm.Drag(628, 183, 32, 1)
  winFormsGameForm.Drag(311, 332, 33, 0)
  winFormsGameForm.Drag(519, 476, 53, 12)
  winFormsGameForm.Keys("car.txt")
  winFormsGameForm.Drag(738, 480, 47, 2)
  winFormsGameForm.Drag(553, 528, 47, 2)
  winFormsGameForm.Keys("car.txt")
  winFormsGameForm.Drag(777, 532, 60, 3)
  winFormsGameForm.Drag(291, 636, 41, -5)
  winFormsGameForm.Close()